### ISSUE TITLE
Chris P.: Picking tokens for reports

### ISSUE THREAD

**Issue by cjpatton** [cpriebe/draft-priebe-ppm-dap-reportauth#1]
> At the time of upload, the client MUST select one authentication token
for each of the Aggregators.

MUST the token be the same for both report shares? If so, is there an enforcement mechanism?

> The Client MUST only use a token once per
task. However, the client MAY re-use the token for a different task. If
the client has no unused authentication token left or the client has not
obtained tokens for a participating Aggregator, it MUST abort the
upload.

What's the intent of the first "MUST"? Note that DAP allows Clients to potentially upload multiple reports for the same task. (Tasks can be comprised of multiple batches of reports, with an aggregate being computed for each batch.) To support this we'd need to allow the Client to use multiple tokens for the same task.

**Comment by cpriebe** [comment]
I believe this has been addressed
