### ISSUE TITLE
Remove ExtensionType field from ReportAuth

### ISSUE THREAD

**Issue by divergentdave** [cpriebe/draft-priebe-ppm-dap-reportauth#9]
The DAP definition of the `Extension` struct is as follows.

```
struct {
  ExtensionType extension_type;
  opaque extension_data<0..2^16-1>;
} Extension;
```

The `ReportAuth` struct should not include its own extension type, rather, the encoded `ReportAuth` value should be included as `Extension.extension_data`, and the extension type should only appear a layer higher in `Extension.extension_type`. Note that the `extension_data` field will have a two-byte length prefix, which allows aggregators to correctly parse input shares with unknown extensions. (before rejecting them for having unknown extensions) We may want to update Figure 2 with a `Extension` layer between `Extensions` and `ReportAuth` to illustrate this.

**Comment by cpriebe** [comment]
Thanks a lot! This makes sense. I believe this is addressed now.

**Comment by divergentdave** [comment]
LGTM, thanks!
